package otpgo

import (
	"testing"
)

func TestHOTP_Generate(t *testing.T) {
	t.Run("Normal Generation", testHOTPNormalGeneration)
	t.Run("Bad Key", testHOTPBadKey)
	t.Run("Default Params", testHOTPDefaultParams)
	t.Run("Autogenerated Key", testHOTPAutogeneratedKey)
	t.Run("Lower Case Key", testHOTPLowerCaseKey)
}

func testHOTPNormalGeneration(t *testing.T) {
	t.Parallel()

	h := &HOTP{
		Key:       "73QK7D3A3PIZ6NUQQBF4BNFYQBRVUHUQ",
		Counter:   362,
		Algorithm: HmacSHA256,
		Length:    Length6,
	}

	otp, err := h.Generate()
	if err != nil {
		t.Errorf("unexpected error: %s", err)
	}

	if otp != "561655" {
		t.Errorf("wrong hotp\nexpected: %s\n  actual: %s", "561655", otp)
	}
}

func testHOTPBadKey(t *testing.T) {
	t.Parallel()

	h := &HOTP{
		Key:       "invalid-base-32",
		Counter:   363,
		Algorithm: HmacSHA256,
		Length:    Length6,
	}

	_, err := h.Generate()
	expectedErr := ErrorInvalidKey{msg: "illegal base32 data at input byte 7"}
	if err != expectedErr {
		t.Errorf("unexpected error: %s", err)
	}
}

func testHOTPDefaultParams(t *testing.T) {
	t.Parallel()

	h := &HOTP{Key: "73QK7D3A3PIZ6NUQQBF4BNFYQBRVUHUQ"}

	expectedAlg := HmacSHA1
	expectedLength := Length6
	expectedOtp := "958715"

	otp, err := h.Generate()

	if err != nil {
		t.Errorf("unexpected error: %s", err)
	}

	if h.Algorithm != expectedAlg {
		t.Errorf("unexpected hash algorithm\nexpected: %d (SHA1)\n  actual: %d", expectedAlg, h.Algorithm)
	}

	if h.Length != expectedLength {
		t.Errorf("unexpected length\nexpected: %d\n  actual: %d", expectedLength, h.Length)
	}

	if otp != expectedOtp {
		t.Errorf("unexpected hotp\nexpected: %s\n  actual: %s", expectedOtp, otp)
	}
}

func testHOTPAutogeneratedKey(t *testing.T) {
	t.Parallel()

	h := &HOTP{}

	_, err := h.Generate()

	if err != nil {
		t.Errorf("unexpected error: %s", err)
	}

	if h.Key == "" {
		t.Error("expected Key to be populated")
	}
}

func testHOTPLowerCaseKey(t *testing.T) {
	t.Parallel()

	h := &HOTP{Key: "73qk7d3a3piz6nuqqbf4bnfyqbrvuhuq"}

	_, err := h.Generate()

	if err != nil {
		t.Errorf("unexpected error: %s", err)
	}

	if h.Key == "" {
		t.Error("expected Key to be populated")
	}
}

func TestHOTP_Validate(t *testing.T) {
	t.Run("Success", testHOTPValidateSuccess)
	t.Run("Failure", testHOTPValidateFailure)
}

func testHOTPValidateSuccess(t *testing.T) {
	t.Parallel()

	h := &HOTP{
		Key:       "73QK7D3A3PIZ6NUQQBF4BNFYQBRVUHUQ",
		Counter:   362,
		Algorithm: HmacSHA256,
		Length:    Length6,
	}

	// Corresponds to h.Counter 363 which is the expected because h.Generate()
	// will increase the h.Counter before calculating the code.
	expectedOTP := "561655"

	isValid, err := h.Validate(expectedOTP)
	if err != nil {
		t.Errorf("unexpected error: %s", err)
	}

	if !isValid {
		t.Errorf("invalid token\nexpected %s to be valid", expectedOTP)
	}
}

func testHOTPValidateFailure(t *testing.T) {
	t.Parallel()

	invalidOTP := "111111"

	h := &HOTP{Length: Length8}

	isValid, err := h.Validate(invalidOTP)
	if err != nil {
		t.Errorf("unexpected error: %s", err)
	}

	if isValid {
		t.Errorf("unexpected valid token\nexpected %s to be invalid", invalidOTP)
	}
}
